nelmio_api_doc:
    documentation:
        info:
            title: Conduit
            description: Conduit API
            version: 1.0.0
        servers:
            - url: /api
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas:
        path_patterns:
            - ^/api(?!/docs.json$)/+
