kind: pipeline
type: docker
name: default

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
    - ./vendor

- name: build
  image: registry.okami101.io/adr1enbe4udou1n/php-8.0-qa
  environment:
    DATABASE_URL: postgresql://main:main@db/main?serverVersion=14&charset=utf8
    JWT_PASSPHRASE: secret-key
  commands:
  - composer install
  - ./vendor/bin/php-cs-fixer fix --dry-run
  - ./vendor/bin/phpstan analyse
  - sleep 10 # Wait for PostgreSQL service starting
  - php bin/phpunit

- name: image
  image: plugins/docker
  settings:
    registry: registry.okami101.io
    repo: registry.okami101.io/adr1enbe4udou1n/symfony-realworld
    tags: latest
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
    - ./vendor

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: front.okami101.io
    port: 2222
    username: okami
    key:
      from_secret: swarm_ssh_key
    script:
      - docker service update --image registry.okami101.io/adr1enbe4udou1n/symfony-realworld:latest symfonyrealworld_app --with-registry-auth

services:
- name: db
  image: postgres:14
  environment:
    POSTGRES_USER: main
    POSTGRES_PASSWORD: main
    POSTGRES_DB: main_test

trigger:
  event:
  - push
  - pull_request
