kind: pipeline
type: docker
name: default

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
    - ./vendor

- name: build
  image: registry.okami101.io/adr1enbe4udou1n/php-qa:8.0
  environment:
    DATABASE_URL: postgresql://main:main@db/main?serverVersion=14&charset=utf8
  commands:
  - composer install
  - ./vendor/bin/php-cs-fixer fix --dry-run
  - ./vendor/bin/phpstan analyse
  - sleep 10 # Wait for PostgreSQL service starting
  - php bin/console d:m:m --env=test -n
  - php bin/console lexik:jwt:generate-keypair -n
  - php bin/phpunit

- name: image
  image: plugins/docker
  settings:
    registry: registry.okami101.io
    repo: registry.okami101.io/adr1enbe4udou1n/symfony-realworld
    tags: latest
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
    - ./vendor

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: front.okami101.io
    port: 2222
    username: okami
    key:
      from_secret: swarm_ssh_key
    script:
      - docker service update --image registry.okami101.io/adr1enbe4udou1n/symfony-realworld:latest symfonyrealworld_app --with-registry-auth

volumes:
- name: cache
  host:
    path: /tmp/cache

services:
- name: db
  image: postgres:14
  environment:
    POSTGRES_USER: main
    POSTGRES_PASSWORD: main
    POSTGRES_DB: main_test

image_pull_secrets:
- dockerconfig

trigger:
  event:
  - push
  - pull_request
