version: "3"

tasks:
  prepare:
    cmds: []
  install:
    cmds:
      - composer install
  lint:
    cmds:
      - ./vendor/bin/php-cs-fixer fix --dry-run
      - ./vendor/bin/phpstan analyse
  build:
    cmds:
      - php bin/console d:m:m --env=test -n
      - php bin/console lexik:jwt:generate-keypair -n
  test:
    cmds:
      - php bin/phpunit --coverage-clover=coverage.xml
