on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gitea.okami101.io/okami101/phpci:8.5
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: test_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
        with:
          install_args: sonar-scanner-cli
      - name: vendor cache
        uses: actions/cache@v5
        with:
          path: vendor
          key: ${{ runner.os }}-vendor
      - name: sonar cache
        uses: actions/cache@v5
        with:
          path: /root/.sonar/cache
          key: ${{ runner.os }}-sonar
      - run: "mise ci ::: scan"
        env:
          MISE_TASK_RUN_AUTO_INSTALL: false
          PHP_CS_FIXER_IGNORE_ENV: true
          DATABASE_URL: postgresql://test:test@postgres/test?serverVersion=16
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
  image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v6
      - name: vendor cache
        uses: actions/cache@v5
        with:
          path: vendor
          key: ${{ runner.os }}-vendor
      - uses: https://gitea.okami101.io/okami101/actions/docker@main
        with:
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          gitea-token: ${{ secrets.RELEASE_TOKEN }}
          release: true
