doctrine:
    dbal:
        driver: pdo_mysql
        host: "%env(resolve:DATABASE_HOST)%"
        dbname: "%env(resolve:DATABASE_NAME)%"
        port: "%env(int:5432:DATABASE_PORT)%"
        user: "%env(resolve:DATABASE_USER)%"
        password: "%env(resolve:DATABASE_PASSWORD)%"
        replicas:
            replica1:
                host: "%env(resolve:DATABASE_REPLICA_HOST)%"
    orm:
        auto_generate_proxy_classes: false
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
